const scrapingDTO = {
    'etatInfosPerso': '',
    'identifiantsetPhotos': '',
    'monEmail': '',
    'monIdentifiantEtudesenFrance': '',
    'photoIdentite': '',
    'etatCoordonnees': '',
    'contactDetails': [],
    'etatCivil': {},
    'statutParcoursDiplomes': '',
    'statutCV': '',
    'etudes': [],
    'statutLangues': '',
    'testLangueFr': '',
    'statutNiveauFr': '',
    'scolariteFrance': '',
    'etudeduFrancais': '',
    'sejourEnFrance': '',
    'statutNiveauAnglais': '',
    'scolaritenglais': '',
    'examenAnglais': '',
    'autreLangue': '',
    'statutPanierFormation': '',
    'panierFormation': [],
    'listeSoumissionDossier': {},
    'statutDossier': ''
}
